monolog:
  handlers:
    service_loggs:
      type: gelf
      publisher: service_upd_publisher
      formatter: monolog.formatter.gelf_message
      channels: ['!php', '!request', '!security', '!translation', '!doctrine', '!console']
      level: info
    grouped:
      type: whatfailuregroup
      members: [service_loggs]