monolog:
  handlers:
    service_loggs:
      type: gelf
      level: info
      publisher: service_upd_publisher
      formatter: monolog.formatter.gelf_message
    grouped:
      type: whatfailuregroup
      members: [service_loggs]