parameters:
  env(SERVICE_NAME): 'noname-service'
  env(LOGSTASH_HOST): 127.0.0.1
  env(LOGSTASH_PORT): 12201
  
  service_name: '%env(string:SERVICE_NAME)%'
  logstash_host: '%env(string:LOGSTASH_HOST)%'
  logstash_port: '%env(int:LOGSTASH_PORT)%'

services:
  _defaults:
    autowire: true
    public: false
    autoconfigure: true
    
  Playtini\LoggerExtraBundle\:
    resource: '../{Logger,EventListener,Processor}'    
        
  service_upd_publisher:
    class: Gelf\Publisher
    arguments: [ "@gelf.udp_transport" ]

  gelf.udp_transport:
    class: Gelf\Transport\UdpTransport
    arguments: ['%logstash_host%', '%logstash_port%']    